# -*- coding: utf-8 -*-
"""DataCollectionPokemon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12axh-4DB0rUyIwfcRJgkzpCEBVBhsKaq
"""

import requests

URL="https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number"

page=requests.get(URL)

from bs4 import BeautifulSoup

soup = BeautifulSoup(page.content, 'html.parser')

poke_content=soup.find(id='mw-content-text')

poke_tables=poke_content.find_all('table')

pokemon_json = []

for x in range (1,9):
  gen_list=poke_tables[x]
  info_start=3
  info_row=gen_list.contents[info_start]

  for i in range(len(info_row.contents)):
    for i in range(info_start, len(gen_list.contents), 2):
        poke_info=gen_list.contents[i]
        kdex=poke_info.contents[1].text.strip()
        ndex=poke_info.contents[3].text.strip()
        name=poke_info.contents[7].text.strip()
        type1=poke_info.contents[9].text.strip()
        url=poke_info.contents[7].a.get("href")
        url="https://bulbapedia.bulbagarden.net" + url
        if len(poke_info.contents) > 10:
            type2=poke_info.contents[11].text.strip()
            pokemon_json.append({
                "kdex": kdex,
                "ndex": ndex,
                "name": name,
                "type1": type1,
                "type2": type2,
                "url": url
            })
        else:
            pokemon_json.append({
                "kdex": kdex,
                "ndex": ndex,
                "name": name,
                "type1": type1,
                "url": url
            })

pokemon_json

import json
with open('/content/pokemon.json', 'w') as outfile:
    json.dump(pokemon_json, outfile)